apiVersion: v1
kind: Service
metadata:
  name: asgpnt-service
spec:
  selector:
    app: asgpnt                
  ports:
  - protocol: TCP
    port: 80                      
    targetPort: 8080  
    nodePort: 30000            
  type: LoadBalancer  
